@Library('jenkinsLibs') _
def numPrue = $BUILD_NUMBER
pipeline {
    agent any
    stages {
        stage('crear'){
            steps{
                script{
                    mover.crearDir(numPrue)
                }
            }
        }
        stage('copiar'){
            steps{
                script{
                    echo "llega hasta aca"
                }
            }
        }
    }
}