@Library('jenkinsLibs') _
pipeline {
    agent any
    stages {
        stage('build'){
            steps{
                script{
                    sh /home/stiven/scripts/script.sh
                }
            }
        }
    }
}