@Library('jenkinsLibs') _
pipeline {
    agent any
    stages {
        stage('crear'){
            steps{
                script{
                    echo "Creando carpeta..."
                    mover.crearDir()
                }
            }
        }
        stage('Clonar'){
            steps{
                script{
                    echo "Clonar del repo..."
                }
            }
        }
        stage('Mover'){
            steps{
                script{
                    echo "moviendo a documentos..."
                }
            }
        }
    }
}